name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nim-versions: '["version-2-0", "version-2-2", "devel"]'
      test-command: |
        nim -v
        gcc --version
        nimble install -y --depsOnly
        nimble install -y stint
        nimble install -y unittest2
        nimble install -y results
        nimble list --installed --version
        env NIMLANG=c nimble test
