name: CI
on:
  push:
    branches:
      - master
      - test-minver
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@minver
    with:
      install-command: 'nimble --resolver:minver install -y --depsOnly stint unittest2 results'
      test-command: |
        nim -v
        gcc --version
        nimble list --installed --version
        env NIMLANG=c nimble test
        spec_test/run_test.sh
