name: CI
on:
  push:
    branches:
      - master
      - test-new-nimble
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@new-nimble
    with:
      test-command: |
        nim -v
        gcc --version
        nimble --useSystemNim install -y --depsOnly stint unittest2 results
        nimble list --installed --version
        env NIMLANG=c nimble test
        spec_test/run_test.sh
